MESSAGE(STATUS "--- Finding gtest  ---")

FIND_PATH(LIB_GOOGLE_TEST_INCLUDE_DIR gtest/gtest.h)
FIND_LIBRARY(LIB_GOOGLE_TEST NAMES gtest)

IF(NOT GOOGLE_TEST_FIND_QUIETLY)
  IF(LIB_GOOGLE_TEST_INCLUDE_DIR)
    MESSAGE(STATUS "Found GoogleTest include dir: ${LIB_GOOGLE_TEST_INCLUDE_DIR}")
  ENDIF()
  IF(LIB_GOOGLE_TEST)
    MESSAGE(STATUS "Found GoogleTest library: ${LIB_GOOGLE_TEST}")
  ENDIF()
ENDIF()

IF(GoogleTest_FIND_REQUIRED)
  IF(NOT LIB_GOOGLE_TEST_INCLUDE_DIR OR NOT LIB_GOOGLE_TEST)
      MESSAGE(FATAL_ERROR "Could not find GoogleTest")
  ENDIF()
ENDIF()

MESSAGE(STATUS "")

